name: gen-org-contributors

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: thinkasany/organize-contributors@master
        with:
          organize_name: doocs
          github_token: ${{ secrets.ACTION_TOKEN }}
          png_path: profile/images/contributors.png
          json_path: profile/contributors.json
          branch: main
          commit_message: 'chore: update contributors'
          excludes_list: "ImgBotApp, github-actions[bot]"
